### ISSUE TITLE
Proper handling of channels with empty names

### ISSUE THREAD

**Issue by gordopl** [CircuitChaos/OpenMicron#1]
Hello.
Omi doesn't export 'no name' channels. I have some channels with empty name and omi treats them as empty channels which isn't true. Simple change in appletexport.cpp fixes this. Maybe You should change it to ignore channels with name filled with 0xff 0xff... only.

BTW nice job :)

Best regards

**Comment by CircuitChaos** [comment]
Hi @gordopl,

To be honest I didn't know it's even possible to have channels with empty names. I added it in the newest commit, feel free to test :)

Thanks.
